[project]
name = "cs161"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "psutil>=7.2.2",
    "pyutil>=3.3.6",
    "requests>=2.32.5",
]
